// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh-CN'
	| 'zh-TW'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	cli: NamespaceCliTranslation,
	web: NamespaceWebTranslation
}

type RootTranslation = {}

export type NamespaceCliTranslation = {
	'new': {
		prompt: {
			/**
			 * E​n​t​e​r​ ​t​h​e​ ​t​i​t​l​e​ ​o​f​ ​t​h​e​ ​n​e​w​ ​a​r​t​i​c​l​e​:
			 */
			title: string
			/**
			 * E​n​t​e​r​ ​t​h​e​ ​c​a​t​e​g​o​r​y​ ​f​o​r​ ​t​h​e​ ​a​r​t​i​c​l​e​ ​(​o​p​t​i​o​n​a​l​)​:
			 */
			category: string
			/**
			 * E​n​t​e​r​ ​t​a​g​s​ ​f​o​r​ ​t​h​e​ ​a​r​t​i​c​l​e​,​ ​c​o​m​m​a​-​s​e​p​a​r​a​t​e​d​ ​(​o​p​t​i​o​n​a​l​)​:
			 */
			tags: string
		}
		action: {
			/**
			 * E​x​i​t​ ​w​i​t​h​o​u​t​ ​c​r​e​a​t​i​n​g​ ​d​r​a​f​t
			 */
			exit: string
		}
		info: {
			/**
			 * S​u​c​c​e​s​s​f​u​l​l​y​ ​c​r​e​a​t​e​d​ ​a​r​t​i​c​l​e​:​ ​{​f​i​l​e​P​a​t​h​}
			 * @param {string} filePath
			 */
			success_created: RequiredParams<'filePath'>
			/**
			 * O​v​e​r​w​r​i​t​i​n​g​ ​e​x​i​s​t​i​n​g​ ​f​i​l​e​:​ ​{​f​i​l​e​P​a​t​h​}
			 * @param {string} filePath
			 */
			overwrite: RequiredParams<'filePath'>
		}
		error: {
			/**
			 * A​r​t​i​c​l​e​ ​t​i​t​l​e​ ​c​a​n​n​o​t​ ​b​e​ ​e​m​p​t​y​.
			 */
			no_title: string
		}
	}
	pub: {
		prompt: {
			/**
			 * S​e​l​e​c​t​ ​t​h​e​ ​d​r​a​f​t​ ​t​o​ ​p​u​b​l​i​s​h​:
			 */
			select: string
		}
		action: {
			/**
			 * E​x​i​t​ ​w​i​t​h​o​u​t​ ​p​u​b​l​i​s​h​i​n​g
			 */
			exit: string
		}
		info: {
			/**
			 * N​o​ ​d​r​a​f​t​s​ ​f​o​u​n​d​ ​t​o​ ​p​u​b​l​i​s​h​.
			 */
			no_drafts_found: string
			/**
			 * S​u​c​c​e​s​s​f​u​l​l​y​ ​p​u​b​l​i​s​h​e​d​ ​'​{​s​o​u​r​c​e​}​'​ ​t​o​ ​'​{​d​e​s​t​i​n​a​t​i​o​n​}​'​.
			 * @param {string} destination
			 * @param {string} source
			 */
			success_article_published: RequiredParams<'destination' | 'source'>
			/**
			 * C​l​e​a​n​e​d​ ​u​p​ ​e​m​p​t​y​ ​s​o​u​r​c​e​ ​d​i​r​e​c​t​o​r​y​:​ ​{​d​i​r​P​a​t​h​}
			 * @param {string} dirPath
			 */
			info_empty_dir_removed: RequiredParams<'dirPath'>
			/**
			 * P​u​b​l​i​s​h​ ​o​p​e​r​a​t​i​o​n​ ​c​a​n​c​e​l​l​e​d​.
			 */
			publish_cancelled: string
		}
		error: {
			/**
			 * E​r​r​o​r​ ​p​u​b​l​i​s​h​i​n​g​ ​a​r​t​i​c​l​e​:​ ​{​m​e​s​s​a​g​e​}
			 * @param {string} message
			 */
			publish_article: RequiredParams<'message'>
		}
	}
	prompt: {
		/**
		 * F​i​l​e​ ​{​f​i​l​e​P​a​t​h​}​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.​ ​C​h​o​o​s​e​ ​a​n​ ​a​c​t​i​o​n​:
		 * @param {string} filePath
		 */
		file_exists: RequiredParams<'filePath'>
		/**
		 * E​n​t​e​r​ ​a​ ​n​e​w​ ​n​a​m​e​ ​f​o​r​ ​t​h​e​ ​f​i​l​e​ ​(​w​i​t​h​o​u​t​ ​e​x​t​e​n​s​i​o​n​)​:
		 */
		enter_new_name: string
	}
	action: {
		/**
		 * R​e​n​a​m​e​ ​t​h​e​ ​f​i​l​e
		 */
		rename: string
		/**
		 * O​v​e​r​w​r​i​t​e​ ​t​h​e​ ​e​x​i​s​t​i​n​g​ ​f​i​l​e
		 */
		overwrite: string
	}
	info: {
		/**
		 * O​p​e​r​a​t​i​o​n​ ​c​a​n​c​e​l​l​e​d​ ​b​y​ ​u​s​e​r​.
		 */
		cancelled_by_user: string
		/**
		 * T​r​y​ ​r​u​n​n​i​n​g​ ​t​h​e​ ​c​o​m​m​a​n​d​ ​w​i​t​h​ ​t​h​e​ ​{​o​p​t​i​o​n​}​ ​o​p​t​i​o​n​ ​t​o​ ​s​p​e​c​i​f​y​ ​t​h​e​ ​r​o​o​t​ ​d​i​r​e​c​t​o​r​y​.
		 * @param {string} option
		 */
		provide_root_dir_guidance: RequiredParams<'option'>
	}
	error: {
		/**
		 * A​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​:​ ​{​m​e​s​s​a​g​e​}
		 * @param {string} message
		 */
		unexpected: RequiredParams<'message'>
		/**
		 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​:​ ​{​m​e​s​s​a​g​e​}
		 * @param {string} message
		 */
		generic: RequiredParams<'message'>
		/**
		 * F​i​l​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​:​ ​{​f​i​l​e​P​a​t​h​}
		 * @param {string} filePath
		 */
		file_exists: RequiredParams<'filePath'>
		/**
		 * E​r​r​o​r​ ​c​r​e​a​t​i​n​g​ ​f​i​l​e​:​ ​{​m​e​s​s​a​g​e​}
		 * @param {string} message
		 */
		create_file: RequiredParams<'message'>
		/**
		 * F​i​l​e​ ​n​a​m​e​ ​c​a​n​n​o​t​ ​b​e​ ​e​m​p​t​y​.
		 */
		empty_filename: string
		/**
		 * C​a​n​n​o​t​ ​r​e​n​a​m​e​ ​t​o​ ​o​r​i​g​i​n​a​l​ ​f​i​l​e​ ​n​a​m​e​:​ ​{​f​i​l​e​N​a​m​e​}
		 * @param {string} fileName
		 */
		rename_to_original_conflict: RequiredParams<'fileName'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​d​e​t​e​r​m​i​n​e​ ​p​r​o​j​e​c​t​ ​r​o​o​t​:​ ​{​m​e​s​s​a​g​e​}
		 * @param {string} message
		 */
		failed_to_find_root: RequiredParams<'message'>
	}
}

export type NamespaceWebTranslation = {
	common: {
		/**
		 * O​p​e​n
		 */
		open: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * R​e​f​r​e​s​h
		 */
		refresh: string
	}
	navigation: {
		/**
		 * N​a​v​i​g​a​t​i​o​n
		 */
		title: string
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * A​b​o​u​t
		 */
		about: string
		archive: {
			/**
			 * A​r​c​h​i​v​e
			 */
			title: string
			/**
			 * T​i​m​e
			 */
			time: string
			/**
			 * T​a​g​s
			 */
			tags: string
			/**
			 * C​a​t​e​g​o​r​i​e​s
			 */
			categories: string
		}
		/**
		 * L​i​n​k​s
		 */
		friendLinks: string
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * P​r​e​v​i​o​u​s​ ​P​a​g​e
		 */
		prevPage: string
		/**
		 * N​e​x​t​ ​P​a​g​e
		 */
		nextPage: string
		/**
		 * R​e​c​e​n​t​ ​P​o​s​t​s
		 */
		recentPosts: string
	}
	status: {
		/**
		 * T​o​t​a​l​ ​P​o​s​t​s
		 */
		totalPosts: string
		/**
		 * T​o​t​a​l​ ​W​o​r​d​s
		 */
		totalWords: string
		/**
		 * L​a​s​t​ ​U​p​d​a​t​e​d
		 */
		lastUpdated: string
		/**
		 * R​u​n​ ​T​i​m​e
		 */
		runTime: string
		/**
		 * {​0​}​ ​w​o​r​d​{​{​s​}​}
		 * @param {string | number | boolean} 0
		 */
		wordsCount: RequiredParams<'0'>
		/**
		 * {​0​}​ ​m​i​n​u​t​e​{​{​s​}​}
		 * @param {string | number | boolean} 0
		 */
		readTime: RequiredParams<'0'>
		/**
		 * {​0​}​ ​p​o​s​t​{​{​s​}​}
		 * @param {string | number | boolean} 0
		 */
		postsCount: RequiredParams<'0'>
		/**
		 * {​0​}​ ​t​a​g​{​{​s​}​}
		 * @param {string | number | boolean} 0
		 */
		tagsCount: RequiredParams<'0'>
		/**
		 * {​0​}​ ​c​a​t​e​g​o​r​y​{​{​s​}​}
		 * @param {string | number | boolean} 0
		 */
		categoriesCount: RequiredParams<'0'>
	}
	button: {
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * S​u​b​s​c​r​i​b​e
		 */
		subscribe: string
		/**
		 * M​o​r​e
		 */
		more: string
		themeToggle: {
			/**
			 * T​o​g​g​l​e​ ​T​h​e​m​e
			 */
			title: string
			/**
			 * L​i​g​h​t
			 */
			lightMode: string
			/**
			 * D​a​r​k
			 */
			darkMode: string
			/**
			 * S​y​s​t​e​m
			 */
			systemMode: string
		}
	}
	meta: {
		/**
		 * A​u​t​h​o​r
		 */
		author: string
		/**
		 * P​u​b​l​i​s​h​e​d​ ​A​t
		 */
		publishedAt: string
		/**
		 * L​i​c​e​n​s​e
		 */
		license: string
		/**
		 * T​a​g​s
		 */
		tags: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		category: string
		/**
		 * N​o​ ​T​a​g​s
		 */
		unTagged: string
		/**
		 * U​n​c​a​t​e​g​o​r​i​z​e​d
		 */
		unCategorized: string
		/**
		 * W​o​r​d​s​ ​C​o​u​n​t
		 */
		wordsCount: string
		/**
		 * R​e​a​d​i​n​g​ ​T​i​m​e
		 */
		readingTime: string
	}
	info: {
		/**
		 * T​a​b​l​e​ ​o​f​ ​C​o​n​t​e​n​t
		 */
		toc: string
		/**
		 * T​o​o​l​ ​B​a​r
		 */
		toolBar: string
		/**
		 * R​e​a​d​i​n​g​ ​P​e​r​c​e​n​t​a​g​e
		 */
		readingPercentage: string
		/**
		 * C​o​m​m​e​n​t​s
		 */
		comments: string
		/**
		 * R​e​c​e​n​t​ ​C​o​m​m​e​n​t​s
		 */
		recentComments: string
		commentAbbrs: {
			/**
			 * [​I​m​a​g​e​]
			 */
			image: string
			/**
			 * [​L​i​n​k​]
			 */
			link: string
			/**
			 * [​C​o​d​e​]
			 */
			code: string
		}
		/**
		 * B​a​c​k​ ​L​i​n​k​s
		 */
		backLinks: string
		/**
		 * T​h​i​s​ ​i​s​ ​a​ ​d​r​a​f​t​ ​a​n​d​ ​w​i​l​l​ ​o​n​l​y​ ​b​e​ ​d​i​s​p​l​a​y​e​d​ ​i​n​ ​<​c​o​d​e​>​D​E​V​<​/​c​o​d​e​>​ ​m​o​d​e​.​ ​T​o​ ​d​i​s​a​b​l​e​ ​d​r​a​f​t​ ​p​r​e​v​i​e​w​,​ ​p​l​e​a​s​e​ ​m​o​d​i​f​y​ ​<​c​o​d​e​>​{​c​o​n​f​i​g​K​e​y​}​<​/​c​o​d​e​>​ ​t​o​ ​<​c​o​d​e​>​{​c​o​n​f​i​g​V​a​l​u​e​}​<​/​c​o​d​e​>​ ​i​n​ ​<​c​o​d​e​>​{​c​o​n​f​i​g​F​i​l​e​P​a​t​h​}​<​/​c​o​d​e​>​.
		 * @param {string} configFilePath
		 * @param {string} configKey
		 * @param {boolean} configValue
		 */
		devNote: RequiredParams<'configFilePath' | 'configKey' | 'configValue'>
		/**
		 * O​p​e​n​ ​M​e​n​u
		 */
		openMenu: string
		/**
		 * C​l​o​s​e​ ​M​e​n​u
		 */
		closeMenu: string
	}
	search: {
		/**
		 * S​e​a​r​c​h
		 */
		title: string
		/**
		 * S​e​a​r​c​h​ ​A​n​y​t​h​i​n​g​.​.​.
		 */
		placeholder: string
		/**
		 * S​e​a​r​c​h​ ​R​e​s​u​l​t​s
		 */
		searchResults: string
		/**
		 * N​o​ ​R​e​s​u​l​t​s​ ​F​o​u​n​d
		 */
		noSearchResults: string
	}
}

export type Namespaces =
	| 'cli'
	| 'web'

type DisallowNamespaces = {
	/**
	 * reserved for 'cli'-namespace\
	 * you need to use the `./cli/index.ts` file instead
	 */
	cli?: "[typesafe-i18n] reserved for 'cli'-namespace. You need to use the `./cli/index.ts` file instead."

	/**
	 * reserved for 'web'-namespace\
	 * you need to use the `./web/index.ts` file instead
	 */
	web?: "[typesafe-i18n] reserved for 'web'-namespace. You need to use the `./web/index.ts` file instead."
}

export type TranslationFunctions = {
	cli: {
		'new': {
			prompt: {
				/**
				 * Enter the title of the new article:
				 */
				title: () => LocalizedString
				/**
				 * Enter the category for the article (optional):
				 */
				category: () => LocalizedString
				/**
				 * Enter tags for the article, comma-separated (optional):
				 */
				tags: () => LocalizedString
			}
			action: {
				/**
				 * Exit without creating draft
				 */
				exit: () => LocalizedString
			}
			info: {
				/**
				 * Successfully created article: {filePath}
				 */
				success_created: (arg: { filePath: string }) => LocalizedString
				/**
				 * Overwriting existing file: {filePath}
				 */
				overwrite: (arg: { filePath: string }) => LocalizedString
			}
			error: {
				/**
				 * Article title cannot be empty.
				 */
				no_title: () => LocalizedString
			}
		}
		pub: {
			prompt: {
				/**
				 * Select the draft to publish:
				 */
				select: () => LocalizedString
			}
			action: {
				/**
				 * Exit without publishing
				 */
				exit: () => LocalizedString
			}
			info: {
				/**
				 * No drafts found to publish.
				 */
				no_drafts_found: () => LocalizedString
				/**
				 * Successfully published '{source}' to '{destination}'.
				 */
				success_article_published: (arg: { destination: string, source: string }) => LocalizedString
				/**
				 * Cleaned up empty source directory: {dirPath}
				 */
				info_empty_dir_removed: (arg: { dirPath: string }) => LocalizedString
				/**
				 * Publish operation cancelled.
				 */
				publish_cancelled: () => LocalizedString
			}
			error: {
				/**
				 * Error publishing article: {message}
				 */
				publish_article: (arg: { message: string }) => LocalizedString
			}
		}
		prompt: {
			/**
			 * File {filePath} already exists. Choose an action:
			 */
			file_exists: (arg: { filePath: string }) => LocalizedString
			/**
			 * Enter a new name for the file (without extension):
			 */
			enter_new_name: () => LocalizedString
		}
		action: {
			/**
			 * Rename the file
			 */
			rename: () => LocalizedString
			/**
			 * Overwrite the existing file
			 */
			overwrite: () => LocalizedString
		}
		info: {
			/**
			 * Operation cancelled by user.
			 */
			cancelled_by_user: () => LocalizedString
			/**
			 * Try running the command with the {option} option to specify the root directory.
			 */
			provide_root_dir_guidance: (arg: { option: string }) => LocalizedString
		}
		error: {
			/**
			 * An unexpected error occurred: {message}
			 */
			unexpected: (arg: { message: string }) => LocalizedString
			/**
			 * An error occurred: {message}
			 */
			generic: (arg: { message: string }) => LocalizedString
			/**
			 * File already exists: {filePath}
			 */
			file_exists: (arg: { filePath: string }) => LocalizedString
			/**
			 * Error creating file: {message}
			 */
			create_file: (arg: { message: string }) => LocalizedString
			/**
			 * File name cannot be empty.
			 */
			empty_filename: () => LocalizedString
			/**
			 * Cannot rename to original file name: {fileName}
			 */
			rename_to_original_conflict: (arg: { fileName: string }) => LocalizedString
			/**
			 * Failed to determine project root: {message}
			 */
			failed_to_find_root: (arg: { message: string }) => LocalizedString
		}
	}
	web: {
		common: {
			/**
			 * Open
			 */
			open: () => LocalizedString
			/**
			 * Close
			 */
			close: () => LocalizedString
			/**
			 * Refresh
			 */
			refresh: () => LocalizedString
		}
		navigation: {
			/**
			 * Navigation
			 */
			title: () => LocalizedString
			/**
			 * Home
			 */
			home: () => LocalizedString
			/**
			 * About
			 */
			about: () => LocalizedString
			archive: {
				/**
				 * Archive
				 */
				title: () => LocalizedString
				/**
				 * Time
				 */
				time: () => LocalizedString
				/**
				 * Tags
				 */
				tags: () => LocalizedString
				/**
				 * Categories
				 */
				categories: () => LocalizedString
			}
			/**
			 * Links
			 */
			friendLinks: () => LocalizedString
			/**
			 * Menu
			 */
			menu: () => LocalizedString
			/**
			 * Previous Page
			 */
			prevPage: () => LocalizedString
			/**
			 * Next Page
			 */
			nextPage: () => LocalizedString
			/**
			 * Recent Posts
			 */
			recentPosts: () => LocalizedString
		}
		status: {
			/**
			 * Total Posts
			 */
			totalPosts: () => LocalizedString
			/**
			 * Total Words
			 */
			totalWords: () => LocalizedString
			/**
			 * Last Updated
			 */
			lastUpdated: () => LocalizedString
			/**
			 * Run Time
			 */
			runTime: () => LocalizedString
			/**
			 * {0} word{{s}}
			 */
			wordsCount: (arg0: string | number | boolean) => LocalizedString
			/**
			 * {0} minute{{s}}
			 */
			readTime: (arg0: string | number | boolean) => LocalizedString
			/**
			 * {0} post{{s}}
			 */
			postsCount: (arg0: string | number | boolean) => LocalizedString
			/**
			 * {0} tag{{s}}
			 */
			tagsCount: (arg0: string | number | boolean) => LocalizedString
			/**
			 * {0} category{{s}}
			 */
			categoriesCount: (arg0: string | number | boolean) => LocalizedString
		}
		button: {
			/**
			 * Search
			 */
			search: () => LocalizedString
			/**
			 * Subscribe
			 */
			subscribe: () => LocalizedString
			/**
			 * More
			 */
			more: () => LocalizedString
			themeToggle: {
				/**
				 * Toggle Theme
				 */
				title: () => LocalizedString
				/**
				 * Light
				 */
				lightMode: () => LocalizedString
				/**
				 * Dark
				 */
				darkMode: () => LocalizedString
				/**
				 * System
				 */
				systemMode: () => LocalizedString
			}
		}
		meta: {
			/**
			 * Author
			 */
			author: () => LocalizedString
			/**
			 * Published At
			 */
			publishedAt: () => LocalizedString
			/**
			 * License
			 */
			license: () => LocalizedString
			/**
			 * Tags
			 */
			tags: () => LocalizedString
			/**
			 * Category
			 */
			category: () => LocalizedString
			/**
			 * No Tags
			 */
			unTagged: () => LocalizedString
			/**
			 * Uncategorized
			 */
			unCategorized: () => LocalizedString
			/**
			 * Words Count
			 */
			wordsCount: () => LocalizedString
			/**
			 * Reading Time
			 */
			readingTime: () => LocalizedString
		}
		info: {
			/**
			 * Table of Content
			 */
			toc: () => LocalizedString
			/**
			 * Tool Bar
			 */
			toolBar: () => LocalizedString
			/**
			 * Reading Percentage
			 */
			readingPercentage: () => LocalizedString
			/**
			 * Comments
			 */
			comments: () => LocalizedString
			/**
			 * Recent Comments
			 */
			recentComments: () => LocalizedString
			commentAbbrs: {
				/**
				 * [Image]
				 */
				image: () => LocalizedString
				/**
				 * [Link]
				 */
				link: () => LocalizedString
				/**
				 * [Code]
				 */
				code: () => LocalizedString
			}
			/**
			 * Back Links
			 */
			backLinks: () => LocalizedString
			/**
			 * This is a draft and will only be displayed in <code>DEV</code> mode. To disable draft preview, please modify <code>{configKey}</code> to <code>{configValue}</code> in <code>{configFilePath}</code>.
			 */
			devNote: (arg: { configFilePath: string, configKey: string, configValue: boolean }) => LocalizedString
			/**
			 * Open Menu
			 */
			openMenu: () => LocalizedString
			/**
			 * Close Menu
			 */
			closeMenu: () => LocalizedString
		}
		search: {
			/**
			 * Search
			 */
			title: () => LocalizedString
			/**
			 * Search Anything...
			 */
			placeholder: () => LocalizedString
			/**
			 * Search Results
			 */
			searchResults: () => LocalizedString
			/**
			 * No Results Found
			 */
			noSearchResults: () => LocalizedString
		}
	}
}

export type Formatters = {}
